# Generated by Django 3.0.6 on 2020-05-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200512_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
