# Generated by Django 3.0.3 on 2020-04-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='xml_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
