# Generated by Django 3.0.3 on 2020-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200421_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
