# Generated by Django 3.0.3 on 2020-04-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200430_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='store_contact_phine',
            new_name='store_contact_phone',
        ),
    ]
