# Generated by Django 3.0.3 on 2020-05-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200430_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
