# Generated by Django 3.0.3 on 2020-04-21 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('product_link', models.CharField(blank=True, max_length=254, null=True)),
                ('product_image_link', models.CharField(blank=True, max_length=254, null=True)),
                ('product_price', models.CharField(blank=True, max_length=254, null=True)),
                ('product_category', models.CharField(max_length=254, null=True)),
                ('product_description', models.TextField(null=True)),
                ('product_name', models.CharField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
