# Generated by Django 3.0.3 on 2020-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_product_id', models.PositiveIntegerField()),
                ('affiliate_product_name', models.CharField(max_length=254)),
                ('affiliate_link', models.CharField(max_length=254)),
                ('affiliate_user', models.CharField(max_length=254)),
                ('affiliate_ip_address', models.CharField(max_length=254)),
            ],
        ),
    ]
