# Generated by Django 3.0.3 on 2020-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200425_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_available',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
