# Generated by Django 3.0.3 on 2020-04-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
