# Generated by Django 3.0.3 on 2020-04-28 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200428_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
