# Generated by Django 3.0.3 on 2020-05-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='published',
            new_name='active',
        ),
    ]
