# Generated by Django 3.0.3 on 2020-05-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_is_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_quality',
            new_name='is_offer',
        ),
    ]
