# Generated by Django 3.0.3 on 2020-05-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200506_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_description',
        ),
        migrations.AddField(
            model_name='category',
            name='category_banner_link',
            field=models.CharField(default='', max_length=254),
        ),
    ]
