# Generated by Django 3.0.3 on 2020-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200507_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_banner_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
