# Generated by Django 3.0.6 on 2020-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_category_category_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_order',
            field=models.IntegerField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
