# Generated by Django 3.0.6 on 2020-05-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20200512_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_order',
        ),
    ]
