# Generated by Django 3.0.6 on 2020-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_category_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
