# Generated by Django 3.0.6 on 2020-05-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20200512_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_banner_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
