# Generated by Django 3.0.6 on 2020-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20200512_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_banner_link',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
