# Generated by Django 3.0.6 on 2020-05-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20200518_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_short_description',
        ),
    ]
