# Generated by Django 3.0.6 on 2020-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_remove_product_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
